---
# tasks file for ./roles/master
- name: master initialization
  become: yes
  ansible.builtin.command:
    cmd: kubeadm init --apiserver-advertise-address={{ ansible_ssh_host }} --pod-network-cidr=10.244.0.0/16 --service-cidr=10.96.0.0/12
    creates: /etc/kubernetes/admin.conf

- name: modify permission
  become: yes
  ansible.builtin.script: cluster_init.sh {{ ansible_ssh_user }}

- name: download CNI
  ansible.builtin.command:
    cmd: wget -P /tmp https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  args:
    creates: /tmp/kube-flannel.yml

- name: apply flannel CNI
  ansible.builtin.command:
    cmd: kubectl apply -f /tmp/kube-flannel.yml

- name: get token
  become: yes
  ansible.builtin.command:
    cmd: kubeadm token create --print-join-command
  register: joinToken

- name: set vars to hostvars
  set_fact:
    token: "{{ joinToken }}"

- name: check token
  debug:
    msg: "the token is {{ joinToken.stdout }}"
