---
# tasks file for ./roles/master
- name: get control plane certificate key first
  become: yes
  become_method: sudo
  ansible.builtin.command: kubeadm certs certificate-key
  register: certKey

- name: set certKey to hostvars
  set_fact:
    key: "{{ certKey }}"

- name: master initialization
  become: yes
  become_method: sudo
  ansible.builtin.command:
    cmd: kubeadm init --certificate-key {{ certKey.stdout }} --control-plane-endpoint "{{ vip }}:16446" --upload-certs

- name: modify permission
  become: yes
  become_method: sudo
  ansible.builtin.script: cluster_init.sh {{ ansible_ssh_user }}

- name: get woker node join token
  become: yes
  become_method: sudo
  ansible.builtin.command:
    cmd: kubeadm token create --print-join-command
  register: joinToken

- name: set joinToken to hostvars
  set_fact:
    token: "{{ joinToken }}"

- name: check joinToken
  debug:
    msg: "worker node join token is: {{ joinToken.stdout }}"
  
- name: check certKey
  debug:
    msg: "control-plane join token is: {{ joinToken.stdout }} --control-plane --certificate-key {{ certKey.stdout }}"