---
# tasks file for ./roles/master
- name: master initialization
  become: true
  ansible.builtin.command:
    cmd: kubeadm init --apiserver-advertise-address={{ ansible_ssh_host }} --pod-network-cidr=10.244.0.0/16 --service-cidr=10.196.0.0/12 --ignore-preflight-errors=DirAvailable--var-lib-etcd
    creates: /etc/kubernetes/admin.conf

- name: modify permission
  become: true
  ansible.builtin.script: cluster_init.sh {{ ansible_ssh_user }}

- name: download calico operator CNI
  ansible.builtin.command:
    cmd: wget -P /tmp https://raw.githubusercontent.com/projectcalico/calico/v3.24.1/manifests/tigera-operator.yaml
  args:
    creates: /tmp/tigera-operator.yaml

- name: download calico custom CNI
  ansible.builtin.command:
    cmd: wget -P /tmp https://raw.githubusercontent.com/projectcalico/calico/v3.24.1/manifests/custom-resources.yaml
  args:
    creates: /tmp/custom-resources.yaml

- name: apply calico operator CNI
  ansible.builtin.command:
    cmd: kubectl create -f /tmp/tigera-operator.yaml

- name: apply calico custom CNI
  ansible.builtin.command:
    cmd: kubectl create -f /tmp/custom-resources.yaml

- name: get token
  become: true
  ansible.builtin.command:
    cmd: kubeadm token create --print-join-command
  register: joinToken

- name: set vars to hostvars
  set_fact:
    token: "{{ joinToken }}"

- name: check token
  debug:
    msg: "the token is {{ joinToken.stdout }}"
